language: bash
services: docker

env:
  - VERSION=3.5 VARIANT=
  - VERSION=3.5 VARIANT=slim
  - VERSION=3.5 VARIANT=alpine
  - VERSION=3.4 VARIANT=
  - VERSION=3.4 VARIANT=slim
  - VERSION=3.4 VARIANT=alpine
  - VERSION=3.4 VARIANT=wheezy
  - VERSION=3.3 VARIANT=
  - VERSION=3.3 VARIANT=slim
  - VERSION=3.3 VARIANT=alpine
  - VERSION=3.3 VARIANT=wheezy
  - VERSION=3.2 VARIANT=
  - VERSION=3.2 VARIANT=slim
  - VERSION=3.2 VARIANT=alpine
  - VERSION=3.2 VARIANT=wheezy
  - VERSION=2.7 VARIANT=
  - VERSION=2.7 VARIANT=slim
  - VERSION=2.7 VARIANT=alpine
  - VERSION=2.7 VARIANT=wheezy

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="$(awk '$1 == "FROM" { print $2; exit }' onbuild/Dockerfile)${VARIANT:+-$VARIANT}"

script:
  - docker build -t "$image" "${VARIANT:-.}"
  - ~/official-images/test/run.sh "$image"
# the "onbuild" variant has to happen with the base variant because it's FROM it
  - true && [ "$VARIANT" ] || docker build -t "${image}-onbuild" onbuild

after_script:
  - docker images

# vim:set et ts=2 sw=2:
